/**
 * Database exports
 */

export {
  closeDatabase,
  cosineSimilarity,
  type DatabaseConfig,
  deserializeVector,
  getDatabase,
  getDb,
  initDatabase,
  isDatabaseConnected,
  serializeVector,
  transaction,
} from './client';
export {
  addKnowledge,
  type CreateKnowledgeParams,
  deleteKnowledge,
  getGuildKnowledge,
  getKnowledge,
  getKnowledgeCount,
  getKnowledgeTags,
  getUnembeddedKnowledge,
  type KnowledgeEntry,
  type KnowledgeWithScore,
  searchKnowledge,
  searchKnowledgeByEmbedding,
  storeKnowledgeEmbedding,
  updateKnowledge,
} from './knowledge';
export {
  type CreateMemoryParams,
  clearMemories,
  deleteInferredMemories,
  deleteMemoriesByType,
  deleteMemory,
  formatMemoriesForPrompt,
  getMemories,
  getMemoriesByType,
  getMemoriesForPrompt,
  getMemoryCount,
  type MemorySource,
  type MemoryType,
  type SimilarMemory as SimilarMemoryResult,
  type StoredMemory,
  type StoredMemory as Memory, // Alias for convenience
  saveMemory,
  searchMemories,
  updateMemory,
} from './memories';
export {
  formatMessagesForProfile,
  type GetMessagesForProfileParams,
  getMessageByPlatformId,
  getMessageCount,
  getMessagesForProfile,
  getRecentMessages,
  insertMessage,
  type MessageInsert,
  messageExists,
  type ProfileMessage,
  type SearchOptions,
  type SimilarMessage,
  type StoredMessage,
  searchSimilar,
  updateMessageEmbedding,
} from './messages';
export {
  getMigrationStatus,
  loadMigrations,
  type Migration,
  type MigrationRecord,
  type MigrationStatus,
  migrate,
  reset,
  rollback,
} from './migrator';
export {
  canGenerateProfile,
  formatProfileForPrompt,
  getOptOutStatus,
  getProfile,
  type ProfileForPrompt,
  type StoredProfile,
  setOptOut,
  type UpsertProfileParams,
  upsertProfile,
} from './profiles';
export {
  type CreateReminderInput,
  cancelReminder,
  cancelReminderByText,
  createNextOccurrence,
  createReminder,
  getDueReminders,
  getReminder,
  getUserPendingReminders,
  getUserReminderCount,
  markReminderDelivered,
  type Reminder,
  snoozeReminder,
} from './reminders';
export {
  formatGroupsForLog,
  getCachedUserRoles,
  getOrRefreshUserRoles,
  resolveRolesToGroups,
  type UserRoles,
  type UserRolesInput,
  upsertUserRoles,
} from './user-roles';
export {
  getLastSeen,
  getRecentUsers,
  getUserById,
  getUserByPlatformId,
  incrementMessageCount,
  type StoredUser,
  searchUsers,
  type UpsertUserParams,
  upsertUser,
} from './users';
